server:
  port: 80
spring:
  application:
    name: users
  jpa:
    hibernate:
      ddl-auto: create-drop
  #h2 embeded setting
  h2:
    console:
      path : /h2-console
      enabled: true
      settings:
        web-allow-others: true
  #Connection Pool DataSource setting
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:~/test
    username: sa
    password: 

greeting:
  name : Welcome User Service!!